- Python
    - Python is a programming paradism means it supports functional programming and object oriented programming and aslo works with procedure oriented programming 
- Procedure oriented language
    - Procedure oriented means write our programming language using functions and objects and classes
- Object oriented language
    - Object:real world entity or it is a physical entity represented memory 
    - Class:logical entity contains logic of the application

In [ ]:
# syntax for class::
class class_name:
    variables
    method or function

In [1]:
print("hello world")

hello world


In [2]:
8+9

17

In [8]:
class Hi:
    a=10
    b=20
    name="Hello"
    def show():
        print("i am from show() function")

In [9]:
Hi.name

'Hello'

In [10]:
Hi.a

10

In [11]:
Hi.b

20

In [12]:
Hi.show()

i am from show() function


In [15]:
print(Hi.a,Hi.b)

10 20


In [22]:
class Hi:
    name="apssdc"
    program_name='python'
    def display():
        print("i am from display function()")
    def show():
        print("i am from show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())
print(Hi.show())

apssdc python
i am from display function()
None
i am from show function()
None


In [17]:
print(Hi.display())

i am from display function()
None


In [19]:
print(Hi.show())

i am from show function()
None


In [25]:
def display():
        print("i am from display function()")
        return("i am from return statement")
def show():
        print("i am from show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())
print(Hi.show())

apssdc python
i am from display function()
None
i am from show function()
None


In [28]:
class Hello:
    def display():
        print("i am from display function()")
        return("i am from return statement")
    def show():
        print("i am from show function()")
print(Hello.display())
print(Hello.show())

i am from display function()
i am from return statement
i am from show function()
None


In [ ]:
# In java obj declaration:
    # class_name obj_name=new_classname
# In python
    # obj_name=class_name

In [31]:
class Hi:
    name="apssdc"
    program_name='python'
    def display(self):
        print("i am from display function()")
        return("i am from return statement")
    def show():
        print("i am from show function()")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

apssdc python
i am from display function()
i am from return statement


### Constructor
- Construcot:without using object we will call methods 
    - In java::class should be same as method name 
    - In python::we will use one special method to define constructor
    - __init(self)__

In [32]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('hareesh','21A85A0517')
obj.display()

hi hareesh
your roll_no 21A85A0517


### Inheritance
- Inherits something parent class to child class

In [ ]:
class A:
    #a,b=10,20
class B(A):
    #c,d=40,50

In [34]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

40 10
i am from class B
i am from class A


### Python libraries for data science
- Organizing,processing,analyzing the huge amount data
- apply data visulization
- Extracting the data from the source
- Nearly 20 python libraries are there
### Top
- Numpy
- Pandas
- Matplotlib

#### Numpy
- Numpy::(num+py) means numerical data+python
- It is functional package for scientific computing in python
- Numpy is python library
- It is used to create multidimentional arrays for fast operations
    - Its dealing with mathematical,scientific,statical data
- Numpy contains a powerful n-dimentional array object which in the form of row and columns
- We can initilize numpy arrays from nested python list

In [ ]:
# how to install numpy
- pip install numpy

In [36]:
# how to import and use numpy package
import numpy as np

In [37]:
# how to find the mumpy version
np.__version__

'1.20.3'

In [38]:
# how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4]) # single dimentional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [40]:
a2=np.array([[2,3,4],[5,6,7]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


In [41]:
# to know shape of the array 
a2.shape

(2, 3)

In [42]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [43]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
print(ar.dtype)

int32


In [45]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [46]:
print(b.shape)

(2, 2)


In [47]:
b.itemsize

4

In [48]:
b.ndim

2

In [51]:
# range 
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [52]:
# arrange()-third party of numpy library 
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [55]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [59]:
#reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [60]:
# resize of array(its modifies shape and array it self)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3) # resize the no of elements from original array 
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [118]:
# zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [119]:
# one array 
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [120]:
# full array-full(dimensional,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [121]:
np.diag(a)

array([7, 7, 7])

In [122]:
np.full(3,100)

array([100, 100, 100])

In [123]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [124]:
# eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [125]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [127]:
r=np.random.randint(1,10)
r

6

In [128]:
r=np.random.randint(1,19,12).reshape(3,4)
r

array([[11,  6, 14, 14],
       [10,  2,  5,  1],
       [ 4,  5,  4, 18]])

In [129]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.19012594, 0.03016149, 0.73664077],
       [0.19953727, 0.67176167, 0.30761446]])

In [130]:
f=np.random.randn(2,3)
f

array([[-0.14939798,  0.16911161,  0.34165278],
       [-0.97873388,  1.31198888,  1.28692964]])

In [131]:
a=np.random.randint(1,30,(10,3))
a

array([[15,  1,  9],
       [10, 28, 24],
       [17, 10, 21],
       [23, 22, 10],
       [25, 28,  3],
       [15,  6, 14],
       [21,  8, 28],
       [ 2, 15,  6],
       [ 8, 29,  2],
       [18,  9, 18]])

In [132]:
a[1:5]

array([[10, 28, 24],
       [17, 10, 21],
       [23, 22, 10],
       [25, 28,  3]])

In [133]:
a[2:,:2]

array([[17, 10],
       [23, 22],
       [25, 28],
       [15,  6],
       [21,  8],
       [ 2, 15],
       [ 8, 29],
       [18,  9]])

In [134]:
a

array([[15,  1,  9],
       [10, 28, 24],
       [17, 10, 21],
       [23, 22, 10],
       [25, 28,  3],
       [15,  6, 14],
       [21,  8, 28],
       [ 2, 15,  6],
       [ 8, 29,  2],
       [18,  9, 18]])

In [135]:
a>10

array([[ True, False, False],
       [False,  True,  True],
       [ True, False,  True],
       [ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [ True, False,  True],
       [False,  True, False],
       [False,  True, False],
       [ True, False,  True]])

In [136]:
a[a<10]

array([1, 9, 3, 6, 8, 2, 6, 8, 2, 9])

In [137]:
a[a>10].sum()

361

In [138]:
a.min()

1

In [139]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [141]:
print(a+b)
print("************")
print(a-b)
print("__________")
print(a*b)
print("$$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]
************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
__________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [142]:
# 0 to 15-->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [143]:
print(np.mean(a))

7.0


In [144]:
print(np.median(a))

7.0


In [145]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [146]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [147]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
np.log(2)

0.6931471805599453

In [149]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [150]:
np.exp(1)

2.718281828459045

In [151]:
np.sin(0)

0.0

In [152]:
np.sin(30)

-0.9880316240928618

In [153]:
np.cos(30)

0.15425144988758405

In [154]:
np.tan(0)

0.0

In [155]:
np.tan(30)

-6.405331196646276

In [156]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

### Pandas
- Pandas is the data science package 
- It is used for 
    - Data manupulation(modification updatations)
    - Data Analysis
    - Data Cleaning(to remove unnecessary data fro
- Contains mainly two data structures in pandas
    - Series---sequence of a data
    - Data Frames--Data with row and column